import * as stylex from '@stylexjs/stylex'
import { colors, spacing, fontSize, borderRadius, transitions } from '../tokens.stylex'

export const styles = stylex.create({
  panel: {
    position: 'relative',
    flexShrink: 0,
    height: '100%',
    backgroundColor: colors.gray800,
    overflow: 'hidden',
  },
  panelWithBorder: {
    borderRightWidth: '1px',
    borderRightStyle: 'solid',
    borderRightColor: colors.gray800,
  },
  panelNoBorder: {
    borderWidth: 0,
  },
  inner: {
    display: 'flex',
    height: '100%',
    flexDirection: 'column',
  },
  header: {
    paddingLeft: spacing['4'],
    paddingRight: spacing['4'],
    paddingTop: spacing['3'],
    paddingBottom: spacing['3'],
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.gray800,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.gray800,
  },
  title: {
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: colors.gray100,
  },
  messagesContainer: {
    flex: 1,
    overflowY: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: spacing['3'],
    padding: spacing['4'],
  },
  messageRow: {
    display: 'flex',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowAssistant: {
    justifyContent: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    borderRadius: borderRadius.lg,
    paddingLeft: spacing['3'],
    paddingRight: spacing['3'],
    paddingTop: spacing['2'],
    paddingBottom: spacing['2'],
    fontSize: fontSize.sm,
    lineHeight: '1.625',
    transition: `background-color ${transitions.fast}, color ${transitions.fast}`,
  },
  messageBubbleUser: {
    backgroundColor: colors.blue500,
    color: colors.white,
  },
  messageBubbleAssistant: {
    backgroundColor: colors.gray700,
    color: colors.gray100,
  },
  inputContainer: {
    borderTopWidth: '1px',
    borderTopStyle: 'solid',
    borderTopColor: colors.gray800,
    padding: spacing['3'],
    backgroundColor: colors.gray800,
  },
  inputWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing['2'],
  },
  textarea: {
    flex: 1,
    resize: 'none',
    borderRadius: borderRadius.lg,
    backgroundColor: colors.gray900,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.gray700,
    paddingLeft: spacing['3'],
    paddingRight: spacing['3'],
    paddingTop: spacing['2'],
    paddingBottom: spacing['2'],
    fontSize: fontSize.sm,
    color: colors.gray100,
    transition: `box-shadow ${transitions.fast}`,
    '::placeholder': {
      color: colors.gray500,
    },
    ':focus': {
      outline: 'none',
      boxShadow: `0 0 0 2px ${colors.blue500}`,
    },
  },
  sendButton: {
    height: '100%',
    borderRadius: borderRadius.lg,
    backgroundColor: colors.blue600,
    paddingLeft: spacing['4'],
    paddingRight: spacing['4'],
    paddingTop: spacing['2'],
    paddingBottom: spacing['2'],
    fontSize: fontSize.sm,
    fontWeight: '600',
    color: colors.white,
    boxShadow: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    transition: `background-color ${transitions.fast}`,
    ':hover': {
      backgroundColor: colors.blue500,
    },
  },
  resizeHandle: {
    position: 'absolute',
    top: 0,
    right: 0,
    height: '100%',
    width: '1px',
    cursor: 'col-resize',
    backgroundColor: colors.transparent,
    transition: `background-color ${transitions.fast}`,
    ':hover': {
      backgroundColor: 'rgba(55, 65, 81, 0.5)',
    },
  },
})
