import * as stylex from '@stylexjs/stylex'
import { colors, spacing, fontSize, borderRadius, transitions } from '../tokens.stylex'

export const styles = stylex.create({
  title: {
    color: colors.gray100,
    fontSize: fontSize.sm,
    fontWeight: 600,
  },
  textarea: {
    borderColor: colors.gray700,
    borderRadius: borderRadius.lg,
    borderStyle: 'solid',
    borderWidth: '1px',
    flex: '1',
    transition: `box-shadow ${transitions.fast}`,
    backgroundColor: colors.gray900,
    boxShadow: {
      default: null,
      ':focus': `0 0 0 2px ${colors.blue500}`,
    },
    color: colors.gray100,
    cursor: {
      default: 'text',
      ':disabled': 'not-allowed',
    },
    fontSize: fontSize.sm,
    opacity: {
      default: 1,
      ':disabled': 0.5,
    },
    resize: 'none',
    paddingBottom: spacing['2'],
    paddingLeft: spacing['3'],
    paddingRight: spacing['3'],
    paddingTop: spacing['2'],
    '::placeholder': {
      color: colors.gray500,
    },
  },
  sendButton: {
    borderRadius: borderRadius.lg,
    transition: `background-color ${transitions.fast}`,
    backgroundColor: {
      default: colors.blue600,
      ':disabled': colors.gray700,
      ':hover': colors.blue500,
    },
    boxShadow: {
      default: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      ':disabled': 'none',
    },
    color: colors.white,
    cursor: {
      default: 'default',
      ':disabled': 'not-allowed',
    },
    fontSize: fontSize.sm,
    fontWeight: 600,
    opacity: {
      default: 1,
      ':disabled': 0.5,
    },
    height: '100%',
    paddingBottom: spacing['2'],
    paddingLeft: spacing['4'],
    paddingRight: spacing['4'],
    paddingTop: spacing['2'],
  },
  resizeHandle: {
    transition: `background-color ${transitions.fast}`,
    backgroundColor: {
      default: colors.transparent,
      ':hover': 'rgba(55, 65, 81, 0.5)',
    },
    cursor: 'col-resize',
    position: 'absolute',
    height: '100%',
    right: 0,
    top: 0,
    width: '1px',
  },
  resetButton: {
    padding: spacing['1'],
    borderWidth: 0,
    textDecoration: {
      default: 'none',
      ':hover': 'underline',
    },
    backgroundColor: 'transparent',
    color: {
      default: colors.gray400,
      ':hover': colors.gray100,
    },
    cursor: 'pointer',
    fontSize: fontSize.xs,
  },
  panelWithBorder: {
    borderRightColor: colors.gray800,
    borderRightStyle: 'solid',
    borderRightWidth: '1px',
  },
  panelNoBorder: {
    borderWidth: 0,
  },
  panel: {
    overflow: 'hidden',
    backgroundColor: colors.gray800,
    flexShrink: 0,
    position: 'relative',
    height: '100%',
  },
  messagesContainer: {
    padding: spacing['4'],
    flex: '1',
    gap: spacing['3'],
    display: 'flex',
    flexDirection: 'column',
    overflowY: 'auto',
  },
  messageRowUser: {
    justifyContent: 'flex-end',
  },
  messageRowError: {
    justifyContent: 'flex-start',
    width: '100%',
  },
  messageRowAssistant: {
    justifyContent: 'flex-start',
  },
  messageRow: {
    display: 'flex',
  },
  messageErrorText: {
    padding: spacing['2'],
    color: 'red',
    fontFamily: 'monospace',
    fontSize: fontSize.sm,
    whiteSpace: 'pre-wrap',
  },
  messageBubbleUser: {
    backgroundColor: colors.blue500,
    color: colors.white,
  },
  messageBubbleAssistant: {
    backgroundColor: colors.gray700,
    color: colors.gray100,
  },
  messageBubble: {
    borderRadius: borderRadius.lg,
    transition: `background-color ${transitions.fast}, color ${transitions.fast}`,
    fontSize: fontSize.sm,
    lineHeight: 1.625,
    whiteSpace: 'pre-wrap',
    maxWidth: '80%',
    paddingBottom: spacing['2'],
    paddingLeft: spacing['3'],
    paddingRight: spacing['3'],
    paddingTop: spacing['2'],
  },
  inputWrapper: {
    gap: spacing['2'],
    alignItems: 'center',
    display: 'flex',
  },
  inputContainer: {
    padding: spacing['3'],
    backgroundColor: colors.gray800,
    borderTopColor: colors.gray800,
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
  },
  inner: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  header: {
    alignItems: 'center',
    backgroundColor: colors.gray800,
    display: 'flex',
    justifyContent: 'space-between',
    borderBottomColor: colors.gray800,
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    paddingBottom: spacing['3'],
    paddingLeft: spacing['4'],
    paddingRight: spacing['4'],
    paddingTop: spacing['3'],
  },
})
