import * as stylex from '@stylexjs/stylex'
import { colors, spacing, fontSize, borderRadius, transitions } from '../tokens.stylex'

export const styles = stylex.create({
  title: {
    color: colors.gray100,
    fontSize: fontSize.sm,
    fontWeight: 600,
  },
  statusDead: {
    color: colors.red400,
  },
  statusAlive: {
    color: colors.green400,
  },
  statusActive: {
    color: colors.blue400,
  },
  resizeHandle: {
    transition: `background-color ${transitions.fast}`,
    backgroundColor: {
      default: colors.transparent,
      ':hover': 'rgba(55, 65, 81, 0.5)',
    },
    cursor: 'col-resize',
    position: 'absolute',
    height: '100%',
    left: 0,
    top: 0,
    width: '1px',
  },
  panelWithBorder: {
    borderLeftColor: colors.gray800,
    borderLeftStyle: 'solid',
    borderLeftWidth: '1px',
  },
  panelNoBorder: {
    borderWidth: 0,
  },
  panel: {
    overflow: 'hidden',
    backgroundColor: colors.gray800,
    flexShrink: 0,
    position: 'relative',
    height: '100%',
  },
  list: {
    padding: 0,
    flex: '1',
    gap: 0,
    display: 'flex',
    flexDirection: 'column',
    borderTopColor: colors.gray800,
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
    overflowY: 'auto',
  },
  itemName: {
    flex: '1',
    overflow: 'hidden',
    fontSize: fontSize.sm,
    fontWeight: 600,
    lineHeight: 1.25,
    textAlign: 'left',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  itemId: {
    color: colors.gray500,
    flexShrink: 0,
    fontSize: fontSize.sm,
    lineHeight: 1.25,
  },
  itemIcon: {
    flexShrink: 0,
    fontSize: fontSize.sm,
    lineHeight: 1.25,
  },
  itemExpandIcon: {
    color: colors.gray400,
    flexShrink: 0,
    fontSize: fontSize.sm,
    lineHeight: 1.25,
  },
  itemDetails: {
    gap: spacing['1'],
    color: colors.gray300,
    display: 'flex',
    flexDirection: 'column',
    fontSize: fontSize.xs,
    marginLeft: spacing['8'],
    marginTop: spacing['1'],
  },
  itemDetailRow: {
    gap: spacing['1'],
    alignItems: 'center',
    display: 'flex',
  },
  itemDetailLabel: {
    color: colors.gray500,
  },
  itemButton: {
    borderRadius: borderRadius.none,
    gap: spacing['1'],
    transition: `background-color ${transitions.fast}`,
    alignItems: 'center',
    backgroundColor: {
      default: colors.gray900,
      ':hover': 'rgba(55, 65, 81, 0.7)',
    },
    color: colors.gray100,
    display: 'flex',
    fontSize: fontSize.sm,
    lineHeight: 1.25,
    paddingBottom: spacing['1'],
    paddingLeft: spacing['1'],
    paddingRight: spacing['1'],
    paddingTop: spacing['1'],
    width: '100%',
  },
  item: {
    borderTopColor: colors.gray800,
    borderTopStyle: 'solid',
    borderTopWidth: '1px',
    paddingBottom: {
      default: 0,
      ':last-child': 0,
    },
    paddingTop: {
      default: 0,
      ':first-child': 0,
    },
  },
  inner: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  header: {
    alignItems: 'center',
    backgroundColor: colors.gray800,
    display: 'flex',
    justifyContent: 'space-between',
    borderBottomColor: colors.gray800,
    borderBottomStyle: 'solid',
    borderBottomWidth: '1px',
    paddingBottom: spacing['3'],
    paddingLeft: spacing['4'],
    paddingRight: spacing['4'],
    paddingTop: spacing['3'],
  },
})
