import * as stylex from '@stylexjs/stylex'
import { colors, spacing, fontSize, borderRadius, transitions } from '../tokens.stylex'

export const styles = stylex.create({
  toggleButton: {
    padding: 0,
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: {
      default: colors.gray400,
      ':hover': colors.gray100,
    },
    cursor: 'pointer',
    fontSize: fontSize.xs,
    position: 'absolute',
    zIndex: 10,
    right: spacing['2'],
  },
  label: {
    color: colors.gray400,
    display: 'block',
    fontSize: fontSize.xs,
    marginBottom: spacing['1'],
  },
  inputWithToggle: {
    paddingRight: '3.5rem',
  },
  inputGroup: {
    alignItems: 'center',
    display: 'flex',
    position: 'relative',
  },
  input: {
    borderColor: colors.gray700,
    borderRadius: borderRadius.DEFAULT,
    borderStyle: 'solid',
    borderWidth: '1px',
    outline: {
      default: null,
      ':focus': 'none',
    },
    backgroundColor: colors.gray800,
    boxShadow: {
      default: null,
      ':focus': `0 0 0 2px ${colors.blue500}`,
    },
    color: colors.gray100,
    fontSize: fontSize.sm,
    paddingBottom: spacing['1'],
    paddingLeft: spacing['2'],
    paddingRight: spacing['2'],
    paddingTop: spacing['1'],
    width: '100%',
  },
  dropdown: {
    padding: spacing['4'],
    borderColor: colors.gray700,
    borderRadius: borderRadius.md,
    borderStyle: 'solid',
    borderWidth: '1px',
    gap: spacing['3'],
    backgroundColor: colors.gray900,
    boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    display: 'flex',
    flexDirection: 'column',
    position: 'absolute',
    zIndex: 20,
    right: spacing['2'],
    top: spacing['12'],
    width: '18rem',
  },
  closeButton: {
    borderColor: colors.gray700,
    borderRadius: borderRadius.DEFAULT,
    borderStyle: 'solid',
    borderWidth: '1px',
    transition: `background-color ${transitions.fast}`,
    backgroundColor: {
      default: colors.gray800,
      ':hover': colors.gray700,
    },
    color: colors.gray100,
    fontSize: fontSize.sm,
    fontWeight: 600,
    paddingBottom: spacing['1'],
    paddingLeft: spacing['2'],
    paddingRight: spacing['2'],
    paddingTop: spacing['1'],
    width: '100%',
  },
  buttonWrapper: {
    paddingTop: spacing['1'],
  },
})
